### PR TITLE
Fix bug to hide negative number in size field

### LINKED ISSUE #562: Prevent writing negative numbers when creating volume claim template
When creating a volumeclaimtemplate the field allows to add negative numbers which cannot be used.
Nobody is going to complain as it pretty obvious and the error message is clear but if you have time maybe it makes sense to add a contraint to disallow typing negative numbers

negativenumbers

### PR DESCRIPTION
**Pull request by sudhirverma**
Fix: #562

### CODE REVIEW

File: src/webview/pipeline/app/widgets/inputwidget.ts [hunk 1]
```diff
@@ -31,18 +31,32 @@ export class InputWidget extends BaseWidget {
...
     this.input.oninput = () => this.getValue(this.input);
     this.input.onblur = () => this.validator();
     this.input.onfocus = () => this.removeError();
     editorInput.appendChild(wrapper);
   }
 
+  blockNegativeNumber(event: KeyboardEvent, input: HTMLInputElement): boolean {
+    if (input?.id === 'size-for-pvc-create-webview') {
+      const matchInputNumber = new RegExp('[0-9]|(Backspace)');
+      if (!event.key.match(matchInputNumber)) {
```
Comment (lstocchi) [inline src/webview/pipeline/app/widgets/inputwidget.ts:53]: Everything works fine but i wanted to ask you why don't you verify the input instead of the keyboardEvent? I mean, every time someone types something, check if the input contains a positive valid number otherwise do not add the last value typed.

In the current way there are some limitations like one cannot move using right/left arrows or delete using canc or users can type numbers like 000020 which javascript convert using octals, not sure kubernetes.

Comment (sudhirverma) [reply src/webview/pipeline/app/widgets/inputwidget.ts:53]: Hi, @lstocchi if we create an html input with type=number write "- or e" in it and try to access it's value via JS you will get an empty string so I use keyboardEvent or alternative, I use input type=text, use regex to allow only digits.

Comment (lstocchi) [reply src/webview/pipeline/app/widgets/inputwidget.ts:53]: Ok. I guess it can be left as it is, it's not an input that will be used so often

**Review by lstocchi — APPROVED** [review]

File: src/webview/pipeline/app/widgets/inputwidget.ts (hunk 1 above)
Comment (sudhirverma) [reply src/webview/pipeline/app/widgets/inputwidget.ts:53]: > some limitations like one cannot move using right/left arrows

but I have fix right/left arrows related problem.
