### PR TITLE
Use 'spawn' function to run 'tkn' cli

### LINKED ISSUE #90: Error: stdout maxBuffer lenght exceeded
On a cluster with a few pipelines and a whole lot of taskrun, I'm running into the following issue. It still loads the pipelines but…

/kind bug

### PR DESCRIPTION
**Pull request by evidolob**
This PR is use [child_process.spawn](https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options) for executing `tkn` cli.

> Note: it also fixes tests in `download.test.ts`, test fails on macos, it seems that they try to create file on filesystem which is in readonly mode.

Fix #90

### CODE REVIEW

File: src/cli.ts [hunk 1]
```diff
@@ -14,19 +14,35 @@ export interface CliExitData {
...
+export function cliCommandToString(command: CliCommand): string {
+    return `${command.cliCommand} ${command.cliArguments.join(' ')}`;
+}
+
 export class Cli implements ICli {
     private static instance: Cli;
     private tknChannel: TknChannel = new TknChannelImpl();
 
-    private constructor() {}
+    private constructor() { }
```
Comment (joshuawilson) [inline src/cli.ts]: if the contstructor is empty I think it should be removed

Comment (evidolob) [reply src/cli.ts]: I think that 'Java style' singleton pattern, we need to refactor that singleton in more TS/JS way.
But agree to remove that

Comment (evidolob) [reply src/cli.ts]: And I even not sure why we need `ICli` interface
